name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.1', '2.7']
        rails: ['70', '71']

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: |
          npm install -g yarn
          yarn install
          mv Gemfile.rails${{matrix.rails}} Gemfile
          bundle install
      - name: Run test
        run: bundle exec rake test
