name: Compatibility test against Rails and Ruby versions
on:
  schedule:
    - cron: '* * * * 1'

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}. Target Rails ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.3', '3.2', '3.1']
        version: ['70', 'main']

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Checkout form_props version
        run: |
          git tag | grep v0.${{ matrix.version }} | tail -1 | xargs git checkout
      - name: Setup project
        run: |
          mv Gemfile.${{ matrix.version }} Gemfile
          npm install -g yarn
          yarn install
          bundle install
      - name: Run test
        run: bundle exec rake test
